apiVersion: apps/v1
kind: Deployment
metadata:
  name: jxserving-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jxserving-gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: registry.jiangxingai.com:5000/jxserving-gateway-linux-amd64:0.1.0
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 9000
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: jxserving-gateway-service
  labels:
    app: jxserving-gateway-svc
spec:
  selector:
    app: jxserving-gateway
  type: NodePort
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 9000